# Generated by Django 4.0 on 2022-01-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='free_text',
            field=models.CharField(max_length=250, null=True, verbose_name='free text'),
        ),
        migrations.AddField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_list', to='core.question'),
        ),
    ]
