# Generated by Django 4.0 on 2022-02-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_allow_multiple_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='pollmode',
            field=models.CharField(choices=[('SU', 'Survey'), ('PO', 'Poll')], default='PO', max_length=2),
        ),
        migrations.AddField(
            model_name='poll',
            name='resultsmode',
            field=models.CharField(choices=[('IM', 'Immediate'), ('AF', 'After'), ('PR', 'Private')], default='IM', max_length=2),
        ),
    ]
