# Generated by Django 4.0 on 2022-02-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_poll_pollmode_poll_resultsmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=2500, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pollmode',
            field=models.CharField(choices=[('SU', 'Survey: show all questions at once'), ('PO', 'Poll: only show one active question')], default='PO', max_length=2),
        ),
        migrations.AlterField(
            model_name='poll',
            name='resultsmode',
            field=models.CharField(choices=[('IM', 'Immediately during voting'), ('AF', 'After voting is done'), ('PR', 'Private: do not show votes to voters')], default='IM', max_length=2),
        ),
    ]
