# Generated by Django 4.0 on 2022-08-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_answer_answer_alter_poll_pollmode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
